/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cabine.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    livro_1_capa_1: THREE.Mesh
    livro_1_capa_2: THREE.Mesh
    livro_1_capa_3: THREE.Mesh
    livro_1_capa_4: THREE.Mesh
    livro_2_capa_1: THREE.Mesh
    livro_2_capa_2: THREE.Mesh
    livro_2_capa_3: THREE.Mesh
    livro_2_capa_4: THREE.Mesh
    livro_2_faixa_2_1: THREE.Mesh
    livro_2_faixa_2_2: THREE.Mesh
    livro_2_faixa_2_3: THREE.Mesh
    livro_2_faixa_1_1: THREE.Mesh
    livro_2_faixa_1_2: THREE.Mesh
    artefato_dourado_ponteiro_1: THREE.Mesh
    artefato_dourado_ponteiro_2: THREE.Mesh
    globo_esfera_1: THREE.Mesh
    globo_esfera_2: THREE.Mesh
    alavanca_1_1: THREE.Mesh
    alavanca_1_2: THREE.Mesh
    alavanca_1_3: THREE.Mesh
    alavanca_2_1: THREE.Mesh
    alavanca_2_2: THREE.Mesh
    alavanca_2_3: THREE.Mesh
    seta_direita_1: THREE.Mesh
    seta_direita_2: THREE.Mesh
    seta_esquerda_1: THREE.Mesh
    seta_esquerda_2: THREE.Mesh
    medidores002: THREE.Mesh
    medidores003: THREE.Mesh
    livro_1_1: THREE.Mesh
    livro_1_2: THREE.Mesh
    livro_1_3: THREE.Mesh
    livro_1_4: THREE.Mesh
    livro_2_1: THREE.Mesh
    livro_2_2: THREE.Mesh
    livro_2_3: THREE.Mesh
    livro_2_4: THREE.Mesh
    teste: THREE.Mesh
    artefato_dourado_1: THREE.Mesh
    artefato_dourado_2: THREE.Mesh
    globo_estrutura002: THREE.Mesh
    esfera_vermelha: THREE.Mesh
    telinha: THREE.Mesh
    luz: THREE.Mesh
    luz001: THREE.Mesh
    luz002: THREE.Mesh
    luz003: THREE.Mesh
    luz004: THREE.Mesh
    luz005: THREE.Mesh
    luz006: THREE.Mesh
    luz007: THREE.Mesh
    luz008: THREE.Mesh
    cena_1: THREE.Mesh
    cena_2: THREE.Mesh
    cena_3: THREE.Mesh
    cena_4: THREE.Mesh
    cena_5: THREE.Mesh
    cena_6: THREE.Mesh
    cena_7: THREE.Mesh
    cena_8: THREE.Mesh
    cena_9: THREE.Mesh
    cena_10: THREE.Mesh
    cena_11: THREE.Mesh
    tela_principal: THREE.Mesh
    mesh: THREE.Mesh
    lampiao: THREE.Mesh
    luz_lampiao: THREE.Mesh
    arvores: THREE.Mesh
    arvores001: THREE.Mesh
    arvores002: THREE.Mesh
  }
  materials: {
    amarelo: THREE.MeshStandardMaterial
    cobre: THREE.MeshStandardMaterial
    ['cobre.001']: THREE.MeshStandardMaterial
    preto: THREE.MeshStandardMaterial
    ouro: THREE.MeshStandardMaterial
    metal_2: THREE.MeshStandardMaterial
    bege: THREE.MeshStandardMaterial
    teste: THREE.MeshStandardMaterial
    madeira: THREE.MeshStandardMaterial
    vermelho: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    verde: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    ciano: THREE.MeshStandardMaterial
    cabo_1: THREE.MeshStandardMaterial
    cabo_2: THREE.MeshStandardMaterial
    lampiao: THREE.MeshStandardMaterial
    ['lampiao-vidro']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cabine.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-5.841, 2.311, 2.844]} rotation={[0.5, 0.762, -0.224]} scale={0.708}>
        <group position={[1.173, -0.007, 0.007]} scale={[1, 1.017, 1]}>
          <mesh geometry={nodes.livro_1_capa_1.geometry} material={materials.amarelo} />
          <mesh geometry={nodes.livro_1_capa_2.geometry} material={materials.cobre} />
          <mesh geometry={nodes.livro_1_capa_3.geometry} material={materials['cobre.001']} />
          <mesh geometry={nodes.livro_1_capa_4.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[5.464, 2.152, 3.052]} rotation={[0.466, -0.729, 0.194]} scale={0.638}>
        <group position={[1.171, -0.01, 0.017]} scale={[1, 1.017, 1]}>
          <mesh geometry={nodes.livro_2_capa_1.geometry} material={materials.amarelo} />
          <mesh geometry={nodes.livro_2_capa_2.geometry} material={materials['cobre.001']} />
          <mesh geometry={nodes.livro_2_capa_3.geometry} material={materials.preto} />
          <mesh geometry={nodes.livro_2_capa_4.geometry} material={materials.cobre} />
        </group>
      </group>
      <group position={[6.452, 1.652, 3.788]} rotation={[0.466, -0.729, 0.194]} scale={0.638}>
        <group position={[-0.004, 0.652, 0]}>
          <group position={[-0.341, 0.051, 0.012]} rotation={[-0.455, 0.735, 0.164]} scale={1.566}>
            <mesh geometry={nodes.livro_2_faixa_2_1.geometry} material={materials.preto} />
            <mesh geometry={nodes.livro_2_faixa_2_2.geometry} material={materials.amarelo} />
            <mesh geometry={nodes.livro_2_faixa_2_3.geometry} material={materials.cobre} />
          </group>
        </group>
        <group position={[0.016, 0.317, 0.005]} scale={0.232}>
          <mesh geometry={nodes.livro_2_faixa_1_1.geometry} material={materials.cobre} />
          <mesh geometry={nodes.livro_2_faixa_1_2.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[4.098, 3.75, -1.284]} rotation={[-0.024, -0.56, -0.885]} scale={0.587}>
        <group position={[0, 0.141, 0.063]} scale={0.103}>
          <mesh geometry={nodes.artefato_dourado_ponteiro_1.geometry} material={materials.ouro} />
          <mesh geometry={nodes.artefato_dourado_ponteiro_2.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[5.417, 3.675, 1.223]} rotation={[0.244, 0.205, -0.311]} scale={0.665}>
        <group rotation={[0, 0, -0.439]} scale={0.854}>
          <mesh geometry={nodes.globo_esfera_1.geometry} material={materials['cobre.001']} />
          <mesh geometry={nodes.globo_esfera_2.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[-4.17, 2.582, 0.483]} rotation={[0.343, 0.637, -0.07]}>
        <group position={[0, 0.562, -0.019]} rotation={[-0.009, -0.019, 0]} scale={[0.102, 0.498, 0.102]}>
          <mesh geometry={nodes.alavanca_1_1.geometry} material={materials.metal_2} />
          <mesh geometry={nodes.alavanca_1_2.geometry} material={materials.cobre} />
          <mesh geometry={nodes.alavanca_1_3.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[-3.559, 2.683, 0.039]} rotation={[0.343, 0.637, -0.07]}>
        <group position={[-0.007, 1.082, -0.018]} rotation={[-0.097, -0.019, -1.575]} scale={[0.111, 0.418, 0.119]}>
          <mesh geometry={nodes.alavanca_2_1.geometry} material={materials.metal_2} />
          <mesh geometry={nodes.alavanca_2_2.geometry} material={materials.cobre} />
          <mesh geometry={nodes.alavanca_2_3.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[2.2, 2.992, -0.32]} rotation={[-0.671, -0.171, -0.153]}>
        <group position={[0.007, -0.008, -0.385]} rotation={[-1.535, 1.556, 3.105]} scale={0.384}>
          <mesh geometry={nodes.seta_direita_1.geometry} material={materials.cobre} />
          <mesh geometry={nodes.seta_direita_2.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[-2.196, 2.988, -0.317]} rotation={[-0.673, 0.17, 0.14]}>
        <group position={[-0.011, -0.001, -0.386]} rotation={[0.679, 1.131, 0.893]} scale={0.384}>
          <mesh geometry={nodes.seta_esquerda_1.geometry} material={materials.cobre} />
          <mesh geometry={nodes.seta_esquerda_2.geometry} material={materials.preto} />
        </group>
      </group>
      <group position={[-4.514, 4.034, -1.34]} rotation={[-0.108, 0.656, 0.229]}>
        <mesh geometry={nodes.medidores002.geometry} material={materials.preto} position={[0, 0.011, -0.122]} rotation={[0.093, 0.042, 0.753]} scale={0.103} />
      </group>
      <group position={[-6.055, 3.803, -0.044]} rotation={[-0.112, 0.695, 0.234]}>
        <mesh geometry={nodes.medidores003.geometry} material={materials.preto} position={[-0.09, 0.111, -0.091]} rotation={[0.087, 0.004, 0.753]} scale={0.103} />
      </group>
      <group position={[-5.386, 2.526, 2.479]} rotation={[1.915, -0.161, -0.775]} scale={0.708}>
        <mesh geometry={nodes.livro_1_1.geometry} material={materials.cobre} />
        <mesh geometry={nodes.livro_1_2.geometry} material={materials['cobre.001']} />
        <mesh geometry={nodes.livro_1_3.geometry} material={materials.bege} />
        <mesh geometry={nodes.livro_1_4.geometry} material={materials.amarelo} />
      </group>
      <group position={[5.961, 2.111, 3.521]} rotation={[0.466, -0.729, 0.194]} scale={0.148}>
        <mesh geometry={nodes.livro_2_1.geometry} material={materials.cobre} />
        <mesh geometry={nodes.livro_2_2.geometry} material={materials['cobre.001']} />
        <mesh geometry={nodes.livro_2_3.geometry} material={materials.bege} />
        <mesh geometry={nodes.livro_2_4.geometry} material={materials.amarelo} />
      </group>
      <mesh geometry={nodes.teste.geometry} material={materials.teste} position={[-0.122, 6.137, -5.516]} rotation={[Math.PI / 2, 0, 0]} scale={13.539} />
      <group position={[4.098, 3.75, -1.284]} rotation={[1.622, -0.119, 0.564]} scale={[0.522, 0.058, 0.522]}>
        <mesh geometry={nodes.artefato_dourado_1.geometry} material={materials.ouro} />
        <mesh geometry={nodes.artefato_dourado_2.geometry} material={materials.madeira} />
      </group>
      <mesh geometry={nodes.globo_estrutura002.geometry} material={materials['cobre.001']} position={[5.534, 2.937, 1.011]} rotation={[0.244, 0.205, 0.128]} scale={[0.072, 0.087, 0.072]} />
      <mesh geometry={nodes.esfera_vermelha.geometry} material={materials.vermelho} position={[3.317, 2.319, 0.869]} rotation={[0.384, -0.445, 0.086]} scale={0.455} />
      <mesh geometry={nodes.telinha.geometry} material={materials.Material} position={[-5.244, 3.176, -0.927]} rotation={[0.139, -0.856, 0.208]} scale={[0.195, 0.195, 0.332]} />
      <mesh geometry={nodes.luz.geometry} material={materials.vermelho} position={[3.598, 2.876, -0.669]} rotation={[0.342, -0.599, 0.058]} scale={[0.05, 0.23, 0.017]} />
      <mesh geometry={nodes.luz001.geometry} material={materials.Material} position={[3.909, 2.826, -0.462]} rotation={[0.342, -0.599, 0.058]} scale={[0.05, 0.23, 0.017]} />
      <mesh geometry={nodes.luz002.geometry} material={materials.verde} position={[4.22, 2.775, -0.254]} rotation={[0.342, -0.599, 0.058]} scale={[0.05, 0.23, 0.017]} />
      <mesh geometry={nodes.luz003.geometry} material={materials.verde} position={[4.532, 2.725, -0.047]} rotation={[0.342, -0.599, 0.058]} scale={[0.05, 0.23, 0.017]} />
      <mesh geometry={nodes.luz004.geometry} material={materials.verde} position={[1.997, 3.449, -2.411]} rotation={[0.413, -0.558, 0.087]} scale={0.06} />
      <mesh geometry={nodes.luz005.geometry} material={materials.verde} position={[2.149, 3.426, -2.318]} rotation={[0.413, -0.558, 0.087]} scale={0.06} />
      <mesh geometry={nodes.luz006.geometry} material={materials.Material} position={[2.302, 3.402, -2.224]} rotation={[0.413, -0.558, 0.087]} scale={0.06} />
      <mesh geometry={nodes.luz007.geometry} material={materials.Material} position={[2.454, 3.378, -2.131]} rotation={[0.413, -0.558, 0.087]} scale={0.06} />
      <mesh geometry={nodes.luz008.geometry} material={materials.vermelho} position={[2.607, 3.354, -2.037]} rotation={[0.413, -0.558, 0.087]} scale={0.06} />
      <group position={[-6.249, 3.891, -0.252]} rotation={[1.882, 0.465, -0.789]} scale={0.679}>
        <mesh geometry={nodes.cena_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.cena_2.geometry} material={materials.bege} />
        <mesh geometry={nodes.cena_3.geometry} material={materials.amarelo} />
        <mesh geometry={nodes.cena_4.geometry} material={materials.vermelho} />
        <mesh geometry={nodes.cena_5.geometry} material={materials.verde} />
        <mesh geometry={nodes.cena_6.geometry} material={materials.ciano} />
        <mesh geometry={nodes.cena_7.geometry} material={materials.cabo_1} />
        <mesh geometry={nodes.cena_8.geometry} material={materials.preto} />
        <mesh geometry={nodes.cena_9.geometry} material={materials.madeira} />
        <mesh geometry={nodes.cena_10.geometry} material={materials.metal_2} />
        <mesh geometry={nodes.cena_11.geometry} material={materials.cabo_2} />
      </group>
      <mesh geometry={nodes.tela_principal.geometry} material={materials.Material} position={[0, 3.668, -0.839]} rotation={[1.142, 0, 0]} />
      <mesh geometry={nodes.mesh.geometry} material={materials.preto} />
      <mesh geometry={nodes.lampiao.geometry} material={materials.lampiao} position={[-3.987, 6.423, -1.352]} rotation={[0, 0.299, 0]} scale={0.431} />
      <mesh geometry={nodes.luz_lampiao.geometry} material={materials['lampiao-vidro']} position={[-3.987, 7.238, -1.352]} rotation={[0, 0.299, 0]} scale={0.385} />
      
    </group>
  )
}

useGLTF.preload('/cabine.glb')
