/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/porta.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    porta_1: THREE.Mesh
    porta_2: THREE.Mesh
    porta_3: THREE.Mesh
    porta_4: THREE.Mesh
    porta_5: THREE.Mesh
    porta_6: THREE.Mesh
    parede: THREE.Mesh
    parede_1: THREE.Mesh
    parede_2: THREE.Mesh
    parede_3: THREE.Mesh
    parede_4: THREE.Mesh
    parede_5: THREE.Mesh
    parede_6: THREE.Mesh
    lampiao: THREE.Mesh
    luz_lampiao: THREE.Mesh
  }
  materials: {
    metal: THREE.MeshStandardMaterial
    madeira1: THREE.MeshStandardMaterial
    metal2: THREE.MeshStandardMaterial
    preto: THREE.MeshStandardMaterial
    vidro: THREE.MeshStandardMaterial
    madeira2: THREE.MeshStandardMaterial
    canos: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    lampiao: THREE.MeshStandardMaterial
    ['lampiao-vidro']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/porta.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-2.919, 3.18, 0.381]}>
        <group position={[0.385, -2.403, 0.101]} scale={0.184}>
          <mesh geometry={nodes.porta_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.porta_2.geometry} material={materials.madeira1} />
          <mesh geometry={nodes.porta_3.geometry} material={materials.metal2} />
          <mesh geometry={nodes.porta_4.geometry} material={materials.preto} />
          <mesh geometry={nodes.porta_5.geometry} material={materials.vidro} />
          <mesh geometry={nodes.porta_6.geometry} material={materials.madeira2} />
        </group>
      </group>
      <group position={[0, 3.854, -0.021]} rotation={[Math.PI / 2, 0, 0]} scale={[39.038, 25.313, 25.313]}>
        <mesh geometry={nodes.parede.geometry} material={materials.madeira2} />
        <mesh geometry={nodes.parede_1.geometry} material={materials.preto} />
        <mesh geometry={nodes.parede_2.geometry} material={materials.madeira1} />
        <mesh geometry={nodes.parede_3.geometry} material={materials.metal} />
        <mesh geometry={nodes.parede_4.geometry} material={materials.metal2} />
        <mesh geometry={nodes.parede_5.geometry} material={materials.canos} />
        <mesh geometry={nodes.parede_6.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.lampiao.geometry} material={materials.lampiao} position={[-5.608, 6.091, 2.237]} scale={0.646} />
      <mesh geometry={nodes.luz_lampiao.geometry} material={materials['lampiao-vidro']} position={[-5.608, 7.312, 2.237]} scale={0.576} />
    </group>
  )
}

useGLTF.preload('/porta.glb')
